apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
spec:
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
  type: {{.Values.serviceType}}
  selector:
    app: {{.Values.name}}
